format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
$time\
\n$character"""

[directory]
style = "bg:#0b1f2d fg:#a3c4f3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#0b1f2d"
format = '[[ $symbol $branch ](fg:#a3c4f3 bg:#0b1f2d)]($style)'

[git_status]
style = "bg:#0b1f2d"
format = '[[($all_status$ahead_behind )](fg:#a3c4f3 bg:#0b1f2d)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[java]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[julia]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[ocaml]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[zig]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[lua]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[ruby]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[dart]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[c]
symbol = "󰬊"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#a3c4f3 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%I:%M" # 12-hour format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
