#!/bin/bash

# Space Navigation
lalt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] && yabai -m space --focus $SPACES[1]
lalt - 2 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[2] ]] && yabai -m space --focus $SPACES[2]
lalt - 3 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[3] ]] && yabai -m space --focus $SPACES[3]
lalt - 4 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[4] ]] && yabai -m space --focus $SPACES[4]
lalt - 5 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[5] ]] && yabai -m space --focus $SPACES[5]

# Window Navigation
lalt - h    : yabai -m window --focus west  || yabai -m display --focus west
lalt - j    : yabai -m window --focus south || yabai -m display --focus south
lalt - k    : yabai -m window --focus north || yabai -m display --focus north
lalt - l    : yabai -m window --focus east  || yabai -m display --focus east

# Toggle window float
lalt + shift - space : yabai -m window --toggle float

# Toggle fullscreen
lalt + shift - f : yabai -m window --toggle zoom-fullscreen

# Equalize size of windows
lalt + shift - e : yabai -m space --balance

# Moving windows in spaces
lalt + shift - h : yabai -m window --warp west || $(yabai -m window --display west && yabai -m display --focus west && yabai -m window --warp last) || yabai -m window --move rel:-10:0
lalt + shift - j : yabai -m window --warp south || $(yabai -m window --display south && yabai -m display --focus south) || yabai -m window --move rel:0:10
lalt + shift - k : yabai -m window --warp north || $(yabai -m window --display north && yabai -m display --focus north) || yabai -m window --move rel:0:-10
lalt + shift - l : yabai -m window --warp east || $(yabai -m window --display east && yabai -m display --focus east && yabai -m window --warp first) || yabai -m window --move rel:10:0

# Toggle split of selected windows node
lalt + shift - s : yabai -m window --toggle split

# Create space
lalt - n : yabai -m space --create

# Destroy space
lalt - d : yabai -m space --destroy

# Moving windows between spaces
lalt + shift - 1 : SPACES=($(yabai m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] \
                  && yabai -m window --space $SPACES[1]
lalt + shift - 2 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[2] ]] \
                  && yabai -m window --space $SPACES[2]
lalt + shift - 3 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[3] ]] \
                  && yabai -m window --space $SPACES[3]
lalt + shift - 4 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[4] ]] \
                  && yabai -m window --space $SPACES[4]
lalt + shift - 5 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[5] ]] \
                  && yabai -m window --space $SPACES[5]
lalt + shift - p : yabai -m window --space prev && yabai -m space --focus prev
lalt + shift - n : yabai -m window --space next && yabai -m space --focus next

# Open apps
lalt - g : open -a /Applications/Ghostty.app/
lalt - b : open -a /Applications/Safari.app/
